import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import LandingPageSection1 from "../containers/LandingPage/LandingPage-section1/LandingPage-Section1";
import NavbarGericht from "../components/NavbarGericht/NavbarGericht";

export default function Home() {
    return (
        <>
            <Head>
                <title>Gericht Restaurant</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="Navbar-Section">
                    <NavbarGericht />
                </div>
                <div className="Main-Section">
                    <LandingPageSection1 />
                </div>
            </main>
        </>
    );
}
